### ISSUE TITLE
How to set ROBOT environment

### ISSUE THREAD

**Issue by hoppss** [neobotix/neo_simulation#1]
When i try to run its launch file, it need to set MAP_NAME and ROBOT environments !
Could you tell me how to set it ?

**Comment by Osiron007** [comment]
Hello hoppss,

thanks for your question.
We added the following to our README.

> Parameters to be set before the bringing up the robot in gazebo
> 
>     In the .bashrc file
> 
>     1.1 ROBOT and MAP_NAME
> 
>         open bashrc file by commanding in the terminal sudo gedit ~/.bashrc and add the following lines:
> 
>         export ROBOT = mpo_500
> 
>         export MAP_NAME = env2map
> 

Best regards,

Jan-Niklas Nieland
Neobotix GmbH
