### ISSUE TITLE
missing imu xacro for mp_500

### ISSUE THREAD

**Issue by fairf4x** [neobotix/neo_simulation#10]
I have cloned the repository to try out the simulation and there was problem with mp_500 model:

```
No such file or directory: /home/fairfax/ROS/middleware/src/neo_simulation/robots/mp_500/xacros/imu.xacro                               
when processing file: /home/fairfax/ROS/middleware/src/neo_simulation/robots/mp_500/mp_500.urdf.xacro
```

The file is indeed missing - I have fixed this by copying and modifying the imu.xacro from mp_400 model but I am not sure whether there is a difference between the two models or not.

**Comment by padhupradheep** [comment]
Hey ! 

Thanks for reporting !

There is no significant difference between the IMU models. 

Best Regards,
Pradheep
