### ISSUE TITLE
In simulation wheels don't seem to move?

### ISSUE THREAD

**Issue by vyi** [neobotix/neo_simulation#12]
I Simulated MPO-700 in ROS Kinetic (kinetic branch) and am able to actuate the robot in x and y directions. I however noticed that the wheels don't seem to rotate and the robot appears to be sliding. 

I also tried with unicycle controls (v and w). Still can't see the wheels rotating or steering. Is this expected behavior? Kindly help.

**Comment by padhupradheep** [comment]
Hey Vivek. 

Yes, it is the expected behavior for the current version of the simulation! We will be updating the repository very soon with a newer simulation model for MPO-700, that would accommodate both rotation and steering.

**Comment by padhupradheep** [comment]
Now we provide the support for the moving casters! 

Pradheep
