### ISSUE TITLE
CMakeLists edit for AWS Robomaker

### ISSUE THREAD

**Issue by arthurrichards77** [neobotix/neo_simulation#19]
Hello

I've used your excellent package as part of a picking task simulation on [AWS Robomaker](https://aws.amazon.com/robomaker/), in which I use some of your macros to construct an MMO-700 with some customizations.  However, I had to edit your CMakeLists.txt to get the macros available from my own package under the colcon build system.  Specifically, I found I needed to add the following to the install section:
```
install(DIRECTORY robots
  DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
)
```
Happy to do this as a fork and a pull request if you like - but it seems a faff for such a tiny update.

Thanks,

Arthur Richards, [Bristol Robotics Lab](http://www.brl.ac.uk)

**Comment by padhupradheep** [comment]
Hello Arthur!

> I've used your excellent package as part of a picking task simulation on AWS Robomaker,

Glad to hear that our packages had helped you ! 

> Happy to do this as a fork and a pull request if you like - but it seems a faff for such a tiny update.

Thanks for letting us know ! We will do the mentioned changes in our next update !
