### ISSUE TITLE
where to find the plugins for the robot and gazebo

### ISSUE THREAD

**Issue by addy1997** [neobotix/neo_simulation#20]
Hello there,

I am trying to create a simulator using this robot for [ignition gazebo](https://ignitionrobotics.org/libs/gazebo). I have a few queries

1. Where do I find the plugins for the robot and gazebo?

**Comment by padhupradheep** [comment]
Hey, that is interesting! 

could you be a bit more specific on what exactly do you mean by "plugin" ? Are you looking for the robot model or the kinematics ?

**Comment by addy1997** [comment]
> Hey, that is interesting!
> 
> could you be a bit more specific on what exactly do you mean by "plugin" ? Are you looking for the robot model or the kinematics ?

@padhupradheep, thanks for replying. By plugins I mean the files to simulate this into gazebo, the model and system plugins.

**Comment by padhupradheep** [comment]
Okay, if you want to simulate our robots in Gazebo, please do follow our [documentation](https://docs.neobotix.de/display/ROSSim/Installation+on+Ubuntu) . We already have everything available to be used in Gazebo.

**Comment by addy1997** [comment]
> Okay, if you want to simulate our robots in Gazebo, please do follow our [documentation](https://docs.neobotix.de/display/ROSSim/Installation+on+Ubuntu) . We already have everything available to be used in Gazebo.

Thanks for pointing out, I really appreciate that.
