### ISSUE TITLE
Warnings in RVIZ with loading local and global cost maps

### ISSUE THREAD

**Issue by borchr27** [neobotix/neo_simulation#28]
Ive been looking into this while trying to run the mp_500 on the 'neo_workshop' map (```export MAP_NAME=neo_workshop```). After cloning the neo_simulation folder into my workspace and building and sourcing I then run the ```roslaunch neo_simulation simulation.launch``` command. I think it is a configuration issue somewhere in a yaml file but I havent found it yet. 

Im trying to run the robot autonomously so I kill the teleop node but then set a goal navigation point I get no path or response.

![image](https://user-images.githubusercontent.com/30349201/159119045-a910fcf4-e717-47e8-9766-571e566c4277.png)

**Comment by padhupradheep** [comment]
Which branch are you using ? 

If melodic, are you sure this [commit](https://github.com/neobotix/neo_simulation/tree/b5abebfdc0af41d3bcc9cff6d6754733ba8e3d6b) is part of your package?

**Comment by borchr27** [comment]
Noetic

**Comment by padhupradheep** [comment]
For now could you try melodic branch , there will be some warnings. You can safely avoid it. I will try to fix your issue for Noetic soon.

**Comment by padhupradheep** [comment]
Hey, I cannot reproduce your problem. Could you check if you had checkeout to noetic branch. Also, please do check, if you had pulled the changes. If possible, could you add the logs ?

**Comment by borchr27** [comment]
ok Ill do some more testing in a few hours

**Comment by borchr27** [comment]
ok Im realizing I was using the melodic neo_sim branch on Ubuntu 20.04 and I need to be using noetic so Im going thru getting the noetic branch for the mp_500 setup and running. 

I pulled the noetic branch and changed the parameters to run the auto navigation with ```simulation.launch``` on the neo_workshop map. Im getting the following warning. And it still isnt loading the local and global cost map like in the image above. Are these supposed to be set as another parameter somewhere or using export?

[ WARN] [1647874968.995537445, 12156.306000000]: global_costmap: Parameter "plugins" not provided, loading pre-Hydro parameters

Note: I did have to fix these files to get it running

- neo_localization.launch
	- comment out the lidar2 line 13
- mp_500.urdf.xacro
	- fix indenting on lines 35 and 135 (line 135 might not matter)

**Comment by padhupradheep** [comment]
> Note: I did have to fix these files to get it running

As far as I know, you do not have to do these changes. xacro does not consider any kind of indentations, as such. 

> I pulled the noetic branch and changed the parameters to run the auto navigation with simulation.launch on the neo_workshop map. Im getting the following warning. And it still isnt loading the local and global cost map like in the image above. Are these supposed to be set as another parameter somewhere or using export?

Your issue looks to me really strange. Are you sure, you are using the same gazebo world and the map?

As far as with the warning is concerned. You can safely avoid it. That does not have an impact. 

Could you clear your build using ``catkin_make clean`` and do the build once again and try it again?

**Comment by borchr27** [comment]
I pulled the noetic branch down again, cleaned, built and set the map. I didn't make any changes except to the simulation launch file to specify the mp_500. Still getting the local_cost map warning and unable to set a nav_goal and auto navigate.

I do have this error:

[FATAL] [1647879792.005838179, 12156.756000000]: Failed to create the neo_local_planner/NeoLocalPlanner planner, are you sure it is properly registered and that the containing library is built? Exception: According to the loaded plugin descriptions the class neo_local_planner/NeoLocalPlanner with base class type nav_core::BaseLocalPlanner does not exist. Declared types are  base_local_planner/TrajectoryPlannerROS dwa_local_planner/DWAPlannerROS
[move_base-9] process has died [pid 43331, exit code 1, cmd /opt/ros/noetic/lib/move_base/move_base __name:=move_base __log:=/home/user/.ros/log/0b6e760e-a933-11ec-91ad-5538d89992a9/move_base-9.log].
log file: /home/user/.ros/log/0b6e760e-a933-11ec-91ad-5538d89992a9/move_base-9*.log

**Comment by borchr27** [comment]
I got it figured out, thank you for your patience
