### ISSUE TITLE
Service /gazebo/spawn_urdf_model takes too long and crashes

### ISSUE THREAD

**Issue by AmmarAlbakri** [neobotix/neo_simulation#31]
I am trying to run the simulation as it is provided in the simulation.launch file but the robot is not spawning in the world and it actually crashes after waiting a certain amount of time (12155.9 s).
System Setup:
Linux Ubuntu 20.04, ROS Noetic
The log is:
[INFO] [1664273133.451913, 0.000000]: Loading model XML from ros parameter robot_description
[INFO] [1664273133.457132, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[ INFO] [1664273133.647593423]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1664273133.648496335]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1664273133.682564666]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1664273133.683561957]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[ INFO] [1664273134.221060119]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1664273134.236771343]: Physics dynamic reconfigure ready.
[INFO] [1664273134.361699, 0.000000]: Calling service /gazebo/spawn_urdf_model
[INFO] [1664273226.082843, 12155.856000]: Spawn status: SpawnModel: Entity pushed to spawn queue, but spawn service timed out waiting for entity to appear in simulation under the name mpo_700
[ERROR] [1664273226.086029, 12155.856000]: Spawn service failed. Exiting.
[ INFO] [1664273226.126631173, 12155.856000000]: NeoLocalizationNode: Got new map with dimensions 4000 x 4000 and cell size 0.05
[ INFO] [1664273226.421361039, 12155.856000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1664273226.423358019, 12155.856000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1664273226.431783112, 12155.856000000]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1664273226.431843769, 12155.856000000]: Starting Laser Plugin (ns = /)
[ INFO] [1664273226.432931719, 12155.856000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1664273226.672805006, 12155.856000000]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1664273226.672840404, 12155.856000000]: Starting Laser Plugin (ns = /)
[ INFO] [1664273226.673595608, 12155.856000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[mpo_700_spawn-6] process has died [pid 573515, exit code 1, cmd /opt/ros/noetic/lib/gazebo_ros/spawn_model -urdf -param robot_description -model mpo_700 __name:=mpo_700_spawn __log:=/home/ammar/.ros/log/ec0efcee-3e4b-11ed-a2a5-eba4cbc793ea/mpo_700_spawn-6.log].
log file: /home/ammar/.ros/log/ec0efcee-3e4b-11ed-a2a5-eba4cbc793ea/mpo_700_spawn-6*.log
[ INFO] [1664273227.107313713, 12155.856000000]: Loading gazebo_ros_control plugin
[ INFO] [1664273227.107396975, 12155.856000000]: Starting gazebo_ros_control plugin in namespace: /
[ INFO] [1664273227.107912673, 12155.856000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [robot_description] on the ROS param server.
[ERROR] [1664273227.221107826, 12155.856000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/mpo_700_caster_front_left_joint
[ERROR] [1664273227.221723751, 12155.856000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/mpo_700_wheel_front_left_joint
[ERROR] [1664273227.222354252, 12155.856000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/mpo_700_caster_back_left_joint
[ERROR] [1664273227.222925304, 12155.856000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/mpo_700_wheel_back_right_joint
[ERROR] [1664273227.223497324, 12155.856000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/mpo_700_caster_back_right_joint
[ERROR] [1664273227.224030442, 12155.856000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/mpo_700_wheel_front_right_joint
[ERROR] [1664273227.224508270, 12155.856000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/mpo_700_caster_front_right_joint
[ERROR] [1664273227.225011610, 12155.856000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/mpo_700_wheel_back_left_joint
[ INFO] [1664273227.228183139, 12155.856000000]: Loaded gazebo_ros_control.
[ WARN] [1664273227.234705037, 12155.856000000]: PlanarMovePlugin (ns = /) missing <cmdTimeout>, defaults to -1.000000
[ WARN] [1664273227.238539328, 12155.866000000]: Timed out waiting for transform from base_link to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 12155.9 timeout was 0.1.

**Comment by padhupradheep** [comment]
Thanks for reporting. 

have you followed all the steps given in the [documentations](https://neobotix-docs.de/ros/ros1/simulation.html) ?

**Comment by AmmarAlbakri** [comment]
Thanks for fast reply.

 I was missing the gazebo models, I solved it by sourcing the models in the bashrc file.
But I am still getting an error with: `Segmentation fault (core dumped)` 
`[gazebo-2] process has died [pid 625102, exit code 139, cmd /opt/ros/noetic/lib/gazebo_ros/gzserver `

Is it related to this or should I open a new issue for this?

**Comment by padhupradheep** [comment]
Not needed, segmentation fault could be anything. Could you please post other logs as well, so we can see what's going on.

**Comment by AmmarAlbakri** [comment]
Unfortunately no, all I have is:
```
[gazebo-2] process has died [pid 631314, exit code 139, cmd /opt/ros/noetic/lib/gazebo_ros/gzserver -e ode /home/ammar/catkin_ws/src/neo_simulation/worlds/neo_workshop.world __name:=gazebo __log:=/home/ammar/.ros/log/551f7042-3e65-11ed-a2a5-eba4cbc793ea/gazebo-2.log].
log file: /home/ammar/.ros/log/551f7042-3e65-11ed-a2a5-eba4cbc793ea/gazebo-2*.log
```
and the mentioned log file  doesn't exist

Although the robot is moving correctly the TF data is missing.

I am reluctant to do any modification to the code because I thought this is an already made simulation, so is it a problem with my machine configuration?

PS: after a few tries the error disappeared and TFs are working, the shocking thing is that I didn't change anything :)

**Comment by padhupradheep** [comment]
Yeah, it’s kind of weird error that you see with Gazebo. We never went in depth debugging the issues. Also it depends on your graphics card. 

Feel free to close the issue, if working fine.
